"""
security.py - Security, sanitization, and DevSecOps protections for Sticky Notes.
Provides path traversal defenses, dangerous filetype blocking, safe URL whitelisting,
and rendered HTML sanitization.
"""

import re
import urllib.parse
from pathlib import Path
from typing import Tuple, Set

# Dangerous executable and script extensions that must never be executed or attached
DANGEROUS_EXTENSIONS: Set[str] = {
    ".exe", ".bat", ".cmd", ".ps1", ".vbs", ".vbe", ".js", ".jse", 
    ".wsf", ".wsh", ".msc", ".msi", ".msp", ".scr", ".com", ".pif", 
    ".application", ".gadget", ".hta", ".cpl", ".jar", ".reg", ".sh"
}

# Strictly allowed URL protocols for external web links
ALLOWED_URL_SCHEMES: Set[str] = {"http", "https", "mailto"}


def is_safe_attachment(file_path: Path) -> Tuple[bool, str]:
    """
    Validates if a file is safe to attach.
    Rejects files with dangerous executable or script extensions.
    """
    suffix = file_path.suffix.lower()
    if suffix in DANGEROUS_EXTENSIONS:
        return False, f"Attachment rejected: Executable or script files ('{suffix}') are prohibited for security."
    
    # Block hidden/system double extensions like 'invoice.pdf.exe'
    stem_lower = file_path.stem.lower()
    for dang in DANGEROUS_EXTENSIONS:
        if stem_lower.endswith(dang):
            return False, f"Attachment rejected: Suspicious double extension detected ('{file_path.name}')."
            
    return True, "File is safe to attach."


def sanitize_filename(stem: str, suffix: str) -> str:
    """
    Sanitizes filename components by stripping directory separators, non-printable
    characters, and reserving only safe alphanumeric, dash, and underscore characters.
    """
    # Clean stem
    clean_stem = re.sub(r'[^a-zA-Z0-9_\-]', '_', stem)[:35]
    if not clean_stem:
        clean_stem = "attachment"
        
    # Clean suffix (must start with dot followed by alphanumeric characters)
    clean_suffix = re.sub(r'[^a-zA-Z0-9\.]', '', suffix.lower())[:10]
    if clean_suffix and not clean_suffix.startswith('.'):
        clean_suffix = f".{clean_suffix}"
        
    return f"{clean_stem}{clean_suffix}"


def is_safe_url(url_str: str, allowed_attachments_dir: Path = None) -> Tuple[bool, str]:
    """
    Validates whether a URL is safe to open.
    Allows:
      1. Web URLs using http://, https://, or mailto:
      2. Local file URLs strictly contained within the application's attachments directory.
    Blocks:
      - Dangerous schemes (javascript:, file:// pointing outside attachments, shell:, ms-msdt:, etc.)
    """
    if not url_str or not isinstance(url_str, str):
        return False, "Empty or invalid URL"

    clean_url = url_str.strip()
    parsed = urllib.parse.urlparse(clean_url)
    scheme = parsed.scheme.lower()

    if scheme in ALLOWED_URL_SCHEMES:
        return True, "Safe external protocol"

    if scheme == "file":
        # Decode and resolve path
        file_path_str = urllib.parse.unquote(parsed.path)
        # Handle Windows drive letters formatted as /C:/...
        if re.match(r'^/[a-zA-Z]:', file_path_str):
            file_path_str = file_path_str.lstrip('/')
            
        target_path = Path(file_path_str).resolve()
        
        if allowed_attachments_dir:
            safe_base = allowed_attachments_dir.resolve()
            try:
                if target_path.is_relative_to(safe_base):
                    # Disallow executing binaries even inside attachments
                    if target_path.suffix.lower() in DANGEROUS_EXTENSIONS:
                        return False, f"Blocked: Target file has dangerous extension ({target_path.suffix})"
                    return True, "Safe local attachment"
            except AttributeError:
                # Python < 3.9 fallback
                if str(target_path).startswith(str(safe_base)):
                    return True, "Safe local attachment"
                    
        return False, "Blocked: Local file access outside attachments folder is restricted for security."

    return False, f"Blocked: Protocol '{scheme}:' is untrusted."


def sanitize_markdown_html(html_str: str) -> str:
    """
    Sanitizes HTML generated by Markdown parser to neutralize active script injections,
    dangerous frames, embeds, and malicious inline event handlers.
    """
    if not html_str:
        return ""

    # Remove <script>...</script> blocks
    cleaned = re.sub(r'(?is)<script.*?>.*?</script>', '', html_str)
    # Remove standalone <script> tags
    cleaned = re.sub(r'(?i)</?script.*?>', '', cleaned)
    # Remove <iframe...>, <embed...>, <object...>, <form...>
    cleaned = re.sub(r'(?i)</?(iframe|embed|object|form|meta|link|base).*?>', '', cleaned)
    # Strip inline JavaScript event handlers (e.g. onload=, onerror=, onclick=)
    cleaned = re.sub(r'(?i)\s+(on[a-z]+)\s*=\s*(["\'][^"\']*["\']|[^\s>]+)', '', cleaned)
    # Strip javascript: URIs in attributes
    cleaned = re.sub(r'(?i)(href|src)\s*=\s*["\']\s*javascript:[^"\']*["\']', 'href="#"', cleaned)

    return cleaned
